import { startTransition, useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import {
  getAdminSemanticBaseModels,
  getAdminSemanticDatasets,
  getAdminSemanticJobs,
  getAdminSemanticModels,
  getAdminSemanticTrainOptions,
  queueSemanticDatasetJob,
  queueSemanticPromotion,
  queueSemanticTrainJob,
} from '../lib/adminApi'
import type {
  SemanticBaseModelOption,
  SemanticDatasetJobCreate,
  SemanticDatasetSummary,
  SemanticJobSummary,
  SemanticModelSummary,
  SemanticTrainAugmentationOption,
  SemanticTrainJobCreate,
  SemanticTrainOptions,
} from '../types/api'
import { AdminRangeField } from './AdminRangeField'
import { AdminSelectionField } from './AdminSelectionField'

type AdminSnapshot = {
  models: SemanticModelSummary[]
  jobs: SemanticJobSummary[]
  datasets: SemanticDatasetSummary[]
}

type DatasetFormState = { dataset_slug: string; augmentation_keys: string[] }
const DEFAULT_DATASET_FORM: DatasetFormState = { dataset_slug: '', augmentation_keys: [] }

type TrainFormState = Omit<SemanticTrainJobCreate, 'requested_by'>
type AdminPageProps = {
  onLogout?: () => void
}

const REFRESH_INTERVAL_MS = 15_000

const FALLBACK_TRAIN_OPTIONS: SemanticTrainOptions = {
  epoch_min: 1,
  epoch_max: 10,
  batch_size_options: [4, 8, 16, 32, 64, 128, 256],
  embed_batch_size_options: [64, 128, 256, 512, 1024],
  augmentation_options: [
    {
      key: 'tag_pairs',
      label: 'Tag pairs',
      description: 'Positive pairs sampled from shared card tags.',
      default_enabled: true,
    },
    {
      key: 'tag_descriptions',
      label: 'Tag descriptions',
      description: 'Anchor text built from tag names and descriptions.',
      default_enabled: true,
    },
    {
      key: 'template_queries',
      label: 'Template queries',
      description: 'Synthetic search-style prompts generated from oracle text.',
      default_enabled: true,
    },
    {
      key: 'llm_queries',
      label: 'LLM queries',
      description: 'Synthetic queries generated by an LLM from card oracle text and metadata.',
      default_enabled: false,
    },
  ],
}

function defaultAugmentationKeys(options: SemanticTrainAugmentationOption[]) {
  return options.filter((option) => option.default_enabled).map((option) => option.key)
}

const DEFAULT_TRAIN_FORM: TrainFormState = {
  dataset_id: '',
  model_slug: '',
  base_model_key: 'mini-lm-l6-v2',
  skip_fine_tune: true,
  epochs: 2,
  batch_size: 64,
  promote_after_register: false,
  embed_batch_size: 256,
}

function formatTimestamp(value?: string | null) {
  if (!value) return 'not yet'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return new Intl.DateTimeFormat('en', {
    month: 'short',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date)
}

function formatBytes(size: number) {
  if (size < 1024 * 1024) {
    return `${Math.max(1, Math.round(size / 1024))} KB`
  }
  return `${(size / (1024 * 1024)).toFixed(1)} MB`
}

function statusTone(status: string) {
  if (status === 'active' || status === 'succeeded' || status === 'ready') return 'bg-ot-ink text-ot-bg'
  if (status === 'running' || status === 'embedding') return 'bg-ot-yellow text-ot-ink'
  if (status === 'pending' || status === 'uploaded') return 'bg-ot-surface text-ot-ink'
  if (status === 'failed') return 'bg-ot-red text-ot-bg'
  return 'bg-ot-line text-ot-ink'
}

function serializeAugmentationKeys(keys: string[]) {
  const normalized = Array.from(new Set(keys.map((key) => key.trim()).filter(Boolean))).sort()
  return normalized.length === 0 ? 'none' : normalized.join(',')
}

export function AdminPage({ onLogout }: AdminPageProps) {
  const [snapshot, setSnapshot] = useState<AdminSnapshot>({ models: [], jobs: [], datasets: [] })
  const [baseModels, setBaseModels] = useState<SemanticBaseModelOption[]>([])
  const [trainOptions, setTrainOptions] = useState<SemanticTrainOptions>(FALLBACK_TRAIN_OPTIONS)
  const [form, setForm] = useState<TrainFormState>(DEFAULT_TRAIN_FORM)
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [datasetForm, setDatasetForm] = useState<DatasetFormState>(DEFAULT_DATASET_FORM)
  const [datasetSubmitting, setDatasetSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [notice, setNotice] = useState<string | null>(null)

  const activePromoteJob = useMemo(
    () => snapshot.jobs.find((job) => job.job_type === 'promote' && (job.status === 'pending' || job.status === 'running')) ?? null,
    [snapshot.jobs]
  )
  const selectedBaseModel = useMemo(
    () => baseModels.find((model) => model.key === form.base_model_key) ?? null,
    [baseModels, form.base_model_key]
  )

  const refreshBoard = useCallback(async (mode: 'initial' | 'refresh' = 'refresh') => {
    if (mode === 'initial') {
      setLoading(true)
    } else {
      setRefreshing(true)
    }

    try {
      const [models, jobs, allowedBaseModels, nextTrainOptions, datasets] = await Promise.all([
        getAdminSemanticModels(),
        getAdminSemanticJobs(),
        getAdminSemanticBaseModels(),
        getAdminSemanticTrainOptions(),
        getAdminSemanticDatasets(),
      ])
      startTransition(() => {
        setSnapshot({ models, jobs, datasets })
        setBaseModels(allowedBaseModels)
        setTrainOptions(nextTrainOptions)
        setForm((current) => {
          const nextBaseModelKey = allowedBaseModels.some((model) => model.key === current.base_model_key)
            ? current.base_model_key
            : allowedBaseModels[0]?.key ?? current.base_model_key
          const nextBatchSize = nextTrainOptions.batch_size_options.includes(current.batch_size)
            ? current.batch_size
            : nextTrainOptions.batch_size_options[0] ?? current.batch_size
          const nextEmbedBatchSize = nextTrainOptions.embed_batch_size_options.includes(current.embed_batch_size)
            ? current.embed_batch_size
            : nextTrainOptions.embed_batch_size_options[0] ?? current.embed_batch_size

          return {
            ...current,
            base_model_key: nextBaseModelKey,
            batch_size: nextBatchSize,
            embed_batch_size: nextEmbedBatchSize,
          }
        })
        setDatasetForm((current) => {
          const filtered = current.augmentation_keys.filter((key) =>
            nextTrainOptions.augmentation_options.some((o) => o.key === key)
          )
          return {
            ...current,
            augmentation_keys: filtered.length > 0 ? filtered : defaultAugmentationKeys(nextTrainOptions.augmentation_options),
          }
        })
        setError(null)
      })
    } catch (nextError) {
      setError(nextError instanceof Error ? nextError.message : 'Unable to load admin registry.')
    } finally {
      if (mode === 'initial') {
        setLoading(false)
      } else {
        setRefreshing(false)
      }
    }
  }, [])

  useEffect(() => {
    void refreshBoard('initial')
  }, [refreshBoard])

  useEffect(() => {
    const intervalId = window.setInterval(() => {
      void refreshBoard('refresh')
    }, REFRESH_INTERVAL_MS)

    return () => window.clearInterval(intervalId)
  }, [refreshBoard])

  const handleTrainField = useCallback(
    <K extends keyof TrainFormState>(key: K, value: TrainFormState[K]) => {
      setForm((current) => ({ ...current, [key]: value }))
    },
    []
  )

  const handleQueueTrain = useCallback(
    async (event: FormEvent<HTMLFormElement>) => {
      event.preventDefault()
      setSubmitting(true)
      setNotice(null)

      try {
        await queueSemanticTrainJob({
          ...form,
          requested_by: 'admin',
          model_slug: form.model_slug.trim(),
        })
        setNotice(`Queued train job for ${form.model_slug.trim() || 'new model'}.`)
        setForm((current) => ({
          ...DEFAULT_TRAIN_FORM,
          dataset_id: current.dataset_id,
          base_model_key: current.base_model_key,
          batch_size: current.batch_size,
          embed_batch_size: current.embed_batch_size,
        }))
        await refreshBoard('refresh')
      } catch (nextError) {
        setError(nextError instanceof Error ? nextError.message : 'Unable to queue train job.')
      } finally {
        setSubmitting(false)
      }
    },
    [form, refreshBoard]
  )

  const handlePromote = useCallback(
    async (modelId: number) => {
      setSubmitting(true)
      setNotice(null)

      try {
        await queueSemanticPromotion(modelId, {
          requested_by: 'admin',
          embed_batch_size: form.embed_batch_size,
        })
        setNotice(`Queued promotion for model ${modelId}.`)
        await refreshBoard('refresh')
      } catch (nextError) {
        setError(nextError instanceof Error ? nextError.message : 'Unable to queue promote job.')
      } finally {
        setSubmitting(false)
      }
    },
    [form.embed_batch_size, refreshBoard]
  )

  const handleQueueDataset = useCallback(
    async (event: FormEvent<HTMLFormElement>) => {
      event.preventDefault()
      setDatasetSubmitting(true)
      setNotice(null)
      try {
        const payload: SemanticDatasetJobCreate = {
          requested_by: 'admin',
          dataset_slug: datasetForm.dataset_slug.trim(),
          augmentation_mode: serializeAugmentationKeys(datasetForm.augmentation_keys),
        }
        await queueSemanticDatasetJob(payload)
        setNotice(`Dataset build queued: ${datasetForm.dataset_slug.trim()}`)
        setDatasetForm((current) => ({ ...current, dataset_slug: '' }))
        await refreshBoard('refresh')
      } catch (nextError) {
        setError(nextError instanceof Error ? nextError.message : 'Unable to queue dataset job.')
      } finally {
        setDatasetSubmitting(false)
      }
    },
    [datasetForm, refreshBoard]
  )

  return (
    <main className="relative min-h-screen overflow-x-clip bg-ot-bg text-ot-ink">
      <style>{`
        .ot-slider {
          -webkit-appearance: none;
          appearance: none;
          background: transparent;
          cursor: pointer;
          outline: none;
        }
        .ot-slider::-webkit-slider-thumb { -webkit-appearance: none; opacity: 0; }
        .ot-slider::-webkit-slider-runnable-track { background: transparent; }
        .ot-slider::-moz-range-thumb { appearance: none; opacity: 0; border: none; }
        .ot-slider::-moz-range-track { background: transparent; }
        .ot-slider::-moz-range-progress { background: transparent; }
      `}</style>
      <div className="fixed inset-y-0 left-0 z-10 w-1.5 bg-ot-red" aria-hidden="true" />
      <div
        className="pointer-events-none absolute inset-0 opacity-60"
        aria-hidden="true"
        style={{
          backgroundImage:
            'repeating-linear-gradient(to bottom, transparent 0, transparent 70px, rgba(17,17,17,0.05) 70px, rgba(17,17,17,0.05) 72px)',
        }}
      />

      <div className="relative z-20 mx-auto flex min-h-screen w-full max-w-[1560px] flex-col px-6 pb-10 pl-11 pt-6 max-[920px]:px-4 max-[920px]:pl-[30px]">
        <header className="grid gap-4 border-b-2 border-ot-ink pb-5 max-[920px]:gap-3">
          <div className="flex items-start justify-between gap-4 max-[920px]:flex-col max-[920px]:items-stretch">
            <div className="grid gap-2">
              <p className="eyebrow">Semantic Registry / Admin</p>
              <h1 className="m-0 max-w-[11ch] font-display text-[clamp(3.8rem,9vw,7rem)] font-black uppercase leading-[0.84] tracking-[-0.04em]">
                Registry board
              </h1>
            </div>

            <div className="grid w-full max-w-[320px] min-w-0 gap-0 self-start border-2 border-ot-ink bg-ot-surface max-[920px]:max-w-none">
              <a
                href="/"
                className="border-b-2 border-ot-ink px-4 py-3 font-display text-[1.1rem] font-black uppercase tracking-[-0.02em] transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] hover:bg-ot-ink hover:text-ot-bg"
              >
                Return to search
              </a>
              {onLogout ? (
                <button
                  type="button"
                  onClick={onLogout}
                  className="border-b-2 border-ot-ink px-4 py-3 text-left font-display text-[1.1rem] font-black uppercase tracking-[-0.02em] transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] hover:bg-ot-red hover:text-ot-bg"
                >
                  Sign out
                </button>
              ) : null}
              <div className="grid grid-cols-4">
                <div className="border-r-2 border-ot-ink px-4 py-3">
                  <p className="eyebrow">Models</p>
                  <p className="m-0 pt-1 font-display text-3xl font-black uppercase leading-none">{snapshot.models.length}</p>
                </div>
                <div className="border-r-2 border-ot-ink px-4 py-3">
                  <p className="eyebrow">Datasets</p>
                  <p className="m-0 pt-1 font-display text-3xl font-black uppercase leading-none">{snapshot.datasets.length}</p>
                </div>
                <div className="border-r-2 border-ot-ink px-4 py-3">
                  <p className="eyebrow">Queued</p>
                  <p className="m-0 pt-1 font-display text-3xl font-black uppercase leading-none">
                    {snapshot.jobs.filter((job) => job.status === 'pending' || job.status === 'running').length}
                  </p>
                </div>
                <div className="px-4 py-3">
                  <p className="eyebrow">Pulse</p>
                  <p className="m-0 pt-1 font-display text-base font-black uppercase leading-none">
                    {refreshing ? 'syncing' : 'steady'}
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="grid gap-2 border-t-2 border-ot-ink pt-3 text-[0.78rem] uppercase tracking-[0.08em] text-ot-muted max-[900px]:text-[0.72rem]">
            <span>Queue new training runs, watch the worker heartbeat, and nominate the next active semantic model without leaving the app.</span>
            {activePromoteJob ? (
              <span className="text-ot-red">
                Promotion lane occupied by job #{activePromoteJob.id}. Clear it before promoting another model.
              </span>
            ) : (
              <span>Promotion lane is open.</span>
            )}
          </div>
        </header>

        {error ? (
          <div className="mt-4 border-2 border-ot-red bg-ot-surface px-4 py-3 text-[0.78rem] uppercase tracking-[0.08em] text-ot-red">
            {error}
          </div>
        ) : null}

        {notice ? (
          <div className="mt-4 border-2 border-ot-ink bg-ot-yellow px-4 py-3 text-[0.78rem] uppercase tracking-[0.08em] text-ot-ink">
            {notice}
          </div>
        ) : null}

        <section className="grid flex-1 grid-cols-[minmax(0,440px)_minmax(0,1fr)] gap-6 pt-6 max-[1180px]:grid-cols-1">
          <div className="grid h-fit gap-6">
            <form
              onSubmit={handleQueueDataset}
              className="grid h-fit gap-0 border-2 border-ot-ink bg-ot-surface"
            >
            <div className="border-b-2 border-ot-ink px-5 py-4">
              <p className="eyebrow">New dataset build</p>
              <h2 className="m-0 pt-2 font-display text-[2.4rem] font-black uppercase leading-[0.88] tracking-[-0.03em]">
                Build a dataset
              </h2>
            </div>

            <label className="grid gap-2 border-b-2 border-ot-ink px-5 py-4">
              <span className="eyebrow">Dataset slug</span>
              <input
                value={datasetForm.dataset_slug}
                onChange={(event) => setDatasetForm((c) => ({ ...c, dataset_slug: event.target.value }))}
                className="min-h-12 w-full min-w-0 border-2 border-ot-ink bg-ot-bg px-3 py-2 text-[0.95rem] outline-none transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] focus:border-ot-red focus:bg-ot-surface"
                placeholder="v3-llm-aug"
                required
              />
            </label>

            <AdminSelectionField
              legend="Augmentation mode"
              name="dataset_augmentation"
              selectionMode="multiple"
              options={trainOptions.augmentation_options.map((o) => ({ value: o.key, label: o.label, description: o.description }))}
              value={datasetForm.augmentation_keys}
              onChange={(keys) => setDatasetForm((c) => ({ ...c, augmentation_keys: keys as string[] }))}
            />

            <div className="px-5 py-4">
              <button
                type="submit"
                disabled={datasetSubmitting || loading}
                className="min-h-12 w-full cursor-pointer border-2 border-ot-ink bg-ot-bg px-4 py-2 font-display text-[1rem] font-black uppercase tracking-[-0.02em] transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] hover:bg-ot-ink hover:text-ot-bg active:opacity-80 disabled:cursor-not-allowed disabled:border-ot-line disabled:text-ot-muted"
              >
                {datasetSubmitting ? 'Queueing…' : 'Queue dataset job'}
              </button>
            </div>
            </form>

            <form
              onSubmit={handleQueueTrain}
              className="grid h-fit gap-0 border-2 border-ot-ink bg-ot-surface"
            >
            <div className="border-b-2 border-ot-ink px-5 py-4">
              <p className="eyebrow">New train run</p>
              <h2 className="m-0 pt-2 font-display text-[2.4rem] font-black uppercase leading-[0.88] tracking-[-0.03em]">
                Queue a candidate
              </h2>
            </div>

            <label className="grid gap-2 border-b-2 border-ot-ink px-5 py-4">
              <span className="eyebrow">Model slug</span>
              <input
                value={form.model_slug}
                onChange={(event) => handleTrainField('model_slug', event.target.value)}
                className="min-h-12 w-full min-w-0 border-2 border-ot-ink bg-ot-bg px-3 py-2 text-[0.95rem] outline-none transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] focus:border-ot-red focus:bg-ot-surface"
                placeholder="oracle-tutor-smoke"
                required
              />
            </label>

            <label className="grid gap-2 border-b-2 border-ot-ink px-5 py-4">
              <span className="eyebrow">Base model</span>
              <select
                value={form.base_model_key}
                onChange={(event) => handleTrainField('base_model_key', event.target.value)}
                className="min-h-12 w-full min-w-0 border-2 border-ot-ink bg-ot-bg px-3 py-2 text-[0.95rem] outline-none transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] focus:border-ot-red focus:bg-ot-surface"
                required
              >
                {baseModels.map((model) => (
                  <option key={model.key} value={model.key}>
                    {model.label}
                  </option>
                ))}
              </select>
              {selectedBaseModel ? (
                <span className="break-words text-[0.76rem] uppercase leading-[1.45] tracking-[0.08em] text-ot-muted">
                  {selectedBaseModel.base_model} / dim {selectedBaseModel.embedding_dim}
                </span>
              ) : null}
            </label>

            <AdminRangeField
              label="Epochs"
              value={form.epochs}
              options={Array.from(
                { length: trainOptions.epoch_max - trainOptions.epoch_min + 1 },
                (_, index) => trainOptions.epoch_min + index
              )}
              rangeValue={form.epochs}
              rangeMin={trainOptions.epoch_min}
              rangeMax={trainOptions.epoch_max}
              onChange={(nextValue) => handleTrainField('epochs', nextValue)}
            />

            <AdminRangeField
              label="Batch size"
              value={form.batch_size}
              options={trainOptions.batch_size_options}
              rangeValue={Math.max(0, trainOptions.batch_size_options.indexOf(form.batch_size))}
              rangeMin={0}
              rangeMax={Math.max(0, trainOptions.batch_size_options.length - 1)}
              onChange={(nextValue) => {
                const selectedValue = trainOptions.batch_size_options[nextValue]
                if (selectedValue !== undefined) {
                  handleTrainField('batch_size', selectedValue)
                }
              }}
            />

            <AdminRangeField
              label="Embed batch size"
              value={form.embed_batch_size}
              options={trainOptions.embed_batch_size_options}
              rangeValue={Math.max(0, trainOptions.embed_batch_size_options.indexOf(form.embed_batch_size))}
              rangeMin={0}
              rangeMax={Math.max(0, trainOptions.embed_batch_size_options.length - 1)}
              onChange={(nextValue) => {
                const selectedValue = trainOptions.embed_batch_size_options[nextValue]
                if (selectedValue !== undefined) {
                  handleTrainField('embed_batch_size', selectedValue)
                }
              }}
            />

            <label className="grid gap-2 border-b-2 border-ot-ink px-5 py-4">
              <span className="eyebrow">Dataset</span>
              {snapshot.datasets.filter((ds) => ds.status === 'ready').length === 0 ? (
                <p className="m-0 text-[0.76rem] uppercase tracking-[0.08em] text-ot-muted">
                  No ready datasets yet — build one above.
                </p>
              ) : (
                <select
                  value={form.dataset_id}
                  onChange={(event) => handleTrainField('dataset_id', event.target.value)}
                  className="min-h-12 w-full min-w-0 border-2 border-ot-ink bg-ot-bg px-3 py-2 text-[0.95rem] outline-none transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] focus:border-ot-red focus:bg-ot-surface"
                  required
                >
                  <option value="">Choose a dataset</option>
                  {snapshot.datasets
                    .filter((ds) => ds.status === 'ready')
                    .map((ds) => (
                      <option key={ds.id} value={ds.id}>
                        {ds.slug} ({ds.augmentation_mode})
                      </option>
                    ))}
                </select>
              )}
            </label>

            <div className="grid border-b-2 border-ot-ink">
              <label className="flex cursor-pointer items-start gap-3 bg-[color-mix(in_srgb,var(--color-ot-red)_5%,var(--color-ot-surface))] px-5 py-4">
                <input
                  type="checkbox"
                  checked={form.skip_fine_tune}
                  onChange={(event) => handleTrainField('skip_fine_tune', event.target.checked)}
                  className="mt-[2px] h-4 w-4 accent-ot-red"
                />
                <span className="grid gap-1">
                  <span className="font-display text-[1.2rem] font-black uppercase leading-none tracking-[-0.02em]">
                    Base-model smoke run
                  </span>
                  <span className="text-[0.76rem] uppercase leading-[1.45] tracking-[0.08em] text-ot-muted">
                    Skip fine-tuning and register an ONNX bundle built directly from the base model.
                  </span>
                </span>
              </label>

              <label className="flex cursor-pointer items-start gap-3 border-t-2 border-ot-ink px-5 py-4">
                <input
                  type="checkbox"
                  checked={form.promote_after_register}
                  onChange={(event) => handleTrainField('promote_after_register', event.target.checked)}
                  className="mt-[2px] h-4 w-4 accent-ot-red"
                />
                <span className="grid gap-1">
                  <span className="font-display text-[1.2rem] font-black uppercase leading-none tracking-[-0.02em]">
                    Queue promotion after register
                  </span>
                  <span className="text-[0.76rem] uppercase leading-[1.45] tracking-[0.08em] text-ot-muted">
                    If the promote lane is occupied, training still succeeds and the warning is recorded with the job.
                  </span>
                </span>
              </label>
            </div>

            <div className="grid gap-3 px-5 py-4">
              <button
                type="submit"
                disabled={submitting || loading}
                className="min-h-14 cursor-pointer border-2 border-ot-ink bg-ot-ink px-4 py-3 font-display text-[1.15rem] font-black uppercase tracking-[-0.02em] text-ot-bg transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] hover:bg-ot-red active:opacity-80 disabled:cursor-not-allowed disabled:bg-ot-muted"
              >
                {submitting ? 'Queueing…' : 'Queue train job'}
              </button>
              <p className="m-0 text-[0.72rem] uppercase leading-[1.55] tracking-[0.08em] text-ot-muted">
                Defaulted for fast operator loops: the smoke-run toggle starts on so you can validate the stack before burning a slow fine-tune.
              </p>
            </div>
            </form>
          </div>

          <div className="grid min-w-0 self-start gap-6">
            <section className="grid gap-0 border-2 border-ot-ink bg-ot-surface">
              <div className="border-b-2 border-ot-ink px-5 py-4">
                <p className="eyebrow">Datasets</p>
                <h2 className="m-0 pt-2 font-display text-[2.1rem] font-black uppercase leading-[0.9] tracking-[-0.03em]">
                  Training datasets
                </h2>
              </div>

              <div className="overflow-x-auto max-[900px]:hidden">
                <table className="min-w-full border-collapse">
                  <thead>
                    <tr className="border-b-2 border-ot-ink bg-ot-bg text-left">
                      {['Dataset', 'Status', 'Augmentation', 'Created'].map((label) => (
                        <th key={label} className="px-4 py-3 font-display text-[0.92rem] font-black uppercase tracking-[0.02em]">
                          {label}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {loading ? (
                      <tr>
                        <td colSpan={4} className="animate-ot-loading-pulse px-4 py-8 text-[0.78rem] uppercase tracking-[0.08em] text-ot-muted">
                          Loading…
                        </td>
                      </tr>
                    ) : snapshot.datasets.length === 0 ? (
                      <tr>
                        <td colSpan={4} className="px-4 py-8 text-[0.78rem] uppercase tracking-[0.08em] text-ot-muted">
                          No datasets built yet.
                        </td>
                      </tr>
                    ) : (
                      snapshot.datasets.map((ds) => (
                        <tr key={ds.id} className="border-b-2 border-ot-line align-top transition-colors duration-150 hover:bg-ot-bg last:border-b-0">
                          <td className="px-4 py-4">
                            <div className="grid gap-1">
                              <span className="break-words font-display text-[1.25rem] font-black uppercase leading-none tracking-[-0.02em]">
                                {ds.slug}
                              </span>
                              {ds.source_semantic_data_version != null && (
                                <span className="text-[0.72rem] uppercase tracking-[0.08em] text-ot-muted">
                                  v{ds.source_semantic_data_version}
                                </span>
                              )}
                            </div>
                          </td>
                          <td className="px-4 py-4">
                            <span className={`inline-block border-2 border-ot-ink px-2 py-1 text-[0.72rem] uppercase tracking-[0.08em] ${statusTone(ds.status)}`}>
                              {ds.status}
                            </span>
                            {ds.error_message ? (
                              <p className="m-0 break-words pt-2 text-[0.72rem] leading-[1.45] text-ot-red">{ds.error_message}</p>
                            ) : null}
                          </td>
                          <td className="px-4 py-4 text-[0.76rem] uppercase tracking-[0.08em] text-ot-muted">
                            {ds.augmentation_mode}
                          </td>
                          <td className="px-4 py-4 text-[0.76rem] uppercase tracking-[0.08em] text-ot-muted">
                            {formatTimestamp(ds.created_at)}
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>

              <div className="hidden max-[900px]:grid">
                {loading ? (
                  <div className="animate-ot-loading-pulse px-5 py-8 text-[0.78rem] uppercase tracking-[0.08em] text-ot-muted">Loading…</div>
                ) : snapshot.datasets.length === 0 ? (
                  <div className="px-5 py-8 text-[0.78rem] uppercase tracking-[0.08em] text-ot-muted">No datasets built yet.</div>
                ) : (
                  snapshot.datasets.map((ds) => (
                    <article key={ds.id} className="grid gap-3 border-b-2 border-ot-line px-5 py-4 last:border-b-0">
                      <div className="flex items-start justify-between gap-2">
                        <span className="font-display text-[1.2rem] font-black uppercase leading-none tracking-[-0.02em]">{ds.slug}</span>
                        <span className={`inline-block shrink-0 border-2 border-ot-ink px-2 py-1 text-[0.68rem] uppercase tracking-[0.08em] ${statusTone(ds.status)}`}>
                          {ds.status}
                        </span>
                      </div>
                      <div className="grid grid-cols-2 gap-3 text-[0.72rem] uppercase tracking-[0.08em] text-ot-muted">
                        <div>
                          <span className="block text-ot-ink">Created</span>
                          {formatTimestamp(ds.created_at)}
                        </div>
                        <div>
                          <span className="block text-ot-ink">Augmentation</span>
                          {ds.augmentation_mode}
                        </div>
                      </div>
                      {ds.error_message ? (
                        <p className="m-0 border-2 border-ot-red px-3 py-3 text-[0.76rem] leading-[1.5] text-ot-red">{ds.error_message}</p>
                      ) : null}
                    </article>
                  ))
                )}
              </div>
            </section>

            <section className="grid gap-0 border-2 border-ot-ink bg-ot-surface">
              <div className="flex items-end justify-between gap-4 border-b-2 border-ot-ink px-5 py-4 max-[720px]:flex-col max-[720px]:items-start">
                <div className="grid gap-2">
                  <p className="eyebrow">Models</p>
                  <h2 className="m-0 font-display text-[2.1rem] font-black uppercase leading-[0.9] tracking-[-0.03em]">
                    Available candidates
                  </h2>
                </div>
                <button
                  type="button"
                  onClick={() => void refreshBoard('refresh')}
                  className="min-h-12 cursor-pointer border-2 border-ot-ink bg-ot-bg px-4 py-2 font-display text-[1rem] font-black uppercase tracking-[-0.02em] transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] hover:bg-ot-ink hover:text-ot-bg active:opacity-80"
                >
                  {refreshing ? 'Refreshing…' : 'Refresh board'}
                </button>
              </div>

              <div className="overflow-x-auto max-[900px]:hidden">
                <table className="min-w-full border-collapse">
                  <thead>
                    <tr className="border-b-2 border-ot-ink bg-ot-bg text-left">
                      {['Model', 'Status', 'Created', 'Artifact', 'Action'].map((label) => (
                        <th key={label} className="px-4 py-3 font-display text-[0.92rem] font-black uppercase tracking-[0.02em]">
                          {label}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {loading ? (
                      <tr>
                        <td colSpan={5} className="animate-ot-loading-pulse px-4 py-8 text-[0.78rem] uppercase tracking-[0.08em] text-ot-muted">
                          Loading…
                        </td>
                      </tr>
                    ) : snapshot.models.length === 0 ? (
                      <tr>
                        <td colSpan={5} className="px-4 py-8 text-[0.78rem] uppercase tracking-[0.08em] text-ot-muted">
                          No models registered yet.
                        </td>
                      </tr>
                    ) : (
                      snapshot.models.map((model) => {
                        const blockedByPromoteLane = !!activePromoteJob && activePromoteJob.model_id !== model.id
                        const disablePromote =
                          submitting ||
                          model.is_active ||
                          model.status === 'embedding' ||
                          blockedByPromoteLane

                        return (
                          <tr key={model.id} className="border-b-2 border-ot-line align-top transition-colors duration-150 hover:bg-ot-bg last:border-b-0">
                            <td className="px-4 py-4">
                              <div className="grid gap-1">
                                <span className="break-words font-display text-[1.25rem] font-black uppercase leading-none tracking-[-0.02em]">
                                  {model.slug}
                                </span>
                                <span className="text-[0.72rem] uppercase tracking-[0.08em] text-ot-muted">
                                  {model.base_model}
                                </span>
                                {model.is_active ? (
                                  <span className="inline-block w-fit border-2 border-ot-ink bg-ot-red px-2 py-1 text-[0.68rem] uppercase tracking-[0.08em] text-ot-bg">
                                    Active
                                  </span>
                                ) : null}
                              </div>
                            </td>
                            <td className="px-4 py-4">
                              <span className={`inline-block border-2 border-ot-ink px-2 py-1 text-[0.72rem] uppercase tracking-[0.08em] ${statusTone(model.status)}`}>
                                {model.status}
                              </span>
                              {model.error_message ? (
                                <p className="m-0 break-words pt-2 text-[0.72rem] leading-[1.45] text-ot-red">{model.error_message}</p>
                              ) : null}
                            </td>
                            <td className="px-4 py-4 text-[0.76rem] uppercase tracking-[0.08em] text-ot-muted">
                              <div>{formatTimestamp(model.created_at)}</div>
                              {model.activated_at ? <div className="pt-2 text-ot-ink">live {formatTimestamp(model.activated_at)}</div> : null}
                            </td>
                            <td className="px-4 py-4 text-[0.76rem] uppercase tracking-[0.08em] text-ot-muted">
                              <div>{formatBytes(model.artifact_size_bytes)}</div>
                              <div className="pt-2 text-ot-ink">dim {model.embedding_dim}</div>
                            </td>
                            <td className="px-4 py-4">
                              <button
                                type="button"
                                disabled={disablePromote}
                                onClick={() => void handlePromote(model.id)}
                                className="min-h-12 cursor-pointer border-2 border-ot-ink bg-ot-bg px-4 py-2 font-display text-[0.98rem] font-black uppercase tracking-[-0.02em] transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] hover:bg-ot-ink hover:text-ot-bg active:opacity-80 disabled:cursor-not-allowed disabled:border-ot-line disabled:bg-ot-bg disabled:text-ot-muted"
                              >
                                {model.is_active ? 'Live now' : blockedByPromoteLane ? 'Lane locked' : 'Promote'}
                              </button>
                            </td>
                          </tr>
                        )
                      })
                    )}
                  </tbody>
                </table>
              </div>

              <div className="hidden max-[900px]:grid">
                {loading ? (
                  <div className="animate-ot-loading-pulse px-5 py-8 text-[0.78rem] uppercase tracking-[0.08em] text-ot-muted">Loading…</div>
                ) : snapshot.models.length === 0 ? (
                  <div className="px-5 py-8 text-[0.78rem] uppercase tracking-[0.08em] text-ot-muted">
                    No models registered yet.
                  </div>
                ) : (
                  snapshot.models.map((model) => {
                    const blockedByPromoteLane = !!activePromoteJob && activePromoteJob.model_id !== model.id
                    const disablePromote =
                      submitting ||
                      model.is_active ||
                      model.status === 'embedding' ||
                      blockedByPromoteLane

                    return (
                      <article key={model.id} className="grid gap-4 border-b-2 border-ot-line px-5 py-4 last:border-b-0">
                        <div className="grid gap-3">
                          <div className="flex flex-wrap items-start justify-between gap-3">
                            <div className="grid min-w-0 gap-1">
                              <span className="break-words font-display text-[1.25rem] font-black uppercase leading-none tracking-[-0.02em]">
                                {model.slug}
                              </span>
                              <span className="break-words text-[0.72rem] uppercase tracking-[0.08em] text-ot-muted">
                                {model.base_model}
                              </span>
                            </div>
                            <div className="flex flex-wrap gap-2">
                              <span
                                className={`inline-block border-2 border-ot-ink px-2 py-1 text-[0.72rem] uppercase tracking-[0.08em] ${statusTone(model.status)}`}
                              >
                                {model.status}
                              </span>
                              {model.is_active ? (
                                <span className="inline-block border-2 border-ot-ink bg-ot-red px-2 py-1 text-[0.68rem] uppercase tracking-[0.08em] text-ot-bg">
                                  Active
                                </span>
                              ) : null}
                            </div>
                          </div>

                          <div className="grid grid-cols-2 gap-3 text-[0.74rem] uppercase tracking-[0.08em] text-ot-muted max-[420px]:grid-cols-1">
                            <div className="grid gap-1 border-2 border-ot-line bg-ot-bg px-3 py-3">
                              <span className="eyebrow">Created</span>
                              <span>{formatTimestamp(model.created_at)}</span>
                              {model.activated_at ? <span className="text-ot-ink">live {formatTimestamp(model.activated_at)}</span> : null}
                            </div>
                            <div className="grid gap-1 border-2 border-ot-line bg-ot-bg px-3 py-3">
                              <span className="eyebrow">Artifact</span>
                              <span>{formatBytes(model.artifact_size_bytes)}</span>
                              <span className="text-ot-ink">dim {model.embedding_dim}</span>
                            </div>
                          </div>

                          {model.error_message ? (
                            <p className="m-0 border-2 border-ot-red bg-[color-mix(in_srgb,var(--color-ot-red)_6%,var(--color-ot-surface))] px-3 py-3 text-[0.74rem] leading-[1.5] text-ot-red">
                              {model.error_message}
                            </p>
                          ) : null}
                        </div>

                        <button
                          type="button"
                          disabled={disablePromote}
                          onClick={() => void handlePromote(model.id)}
                          className="min-h-12 cursor-pointer border-2 border-ot-ink bg-ot-bg px-4 py-2 font-display text-[0.98rem] font-black uppercase tracking-[-0.02em] transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] hover:bg-ot-ink hover:text-ot-bg active:opacity-80 disabled:cursor-not-allowed disabled:border-ot-line disabled:bg-ot-bg disabled:text-ot-muted"
                        >
                          {model.is_active ? 'Live now' : blockedByPromoteLane ? 'Lane locked' : 'Promote'}
                        </button>
                      </article>
                    )
                  })
                )}
              </div>
            </section>

            <section className="grid gap-0 border-2 border-ot-ink bg-ot-surface">
              <div className="border-b-2 border-ot-ink px-5 py-4">
                <p className="eyebrow">Jobs</p>
                <h2 className="m-0 pt-2 font-display text-[2.1rem] font-black uppercase leading-[0.9] tracking-[-0.03em]">
                  Queue and worker pulse
                </h2>
              </div>

              <div className="grid">
                {loading ? (
                  <div className="animate-ot-loading-pulse px-5 py-8 text-[0.78rem] uppercase tracking-[0.08em] text-ot-muted">Loading…</div>
                ) : snapshot.jobs.length === 0 ? (
                  <div className="px-5 py-8 text-[0.78rem] uppercase tracking-[0.08em] text-ot-muted">
                    No jobs queued yet.
                  </div>
                ) : (
                  snapshot.jobs.map((job) => (
                    <article
                      key={job.id}
                      className="grid gap-3 border-b-2 border-ot-line px-5 py-4 last:border-b-0"
                    >
                      <div className="flex items-start justify-between gap-4 max-[720px]:flex-col">
                        <div className="grid gap-2">
                          <div className="flex flex-wrap items-center gap-2">
                            <span className="font-display text-[1.3rem] font-black uppercase leading-none tracking-[-0.02em]">
                              #{job.id} {job.job_type}
                            </span>
                            <span className={`inline-block border-2 border-ot-ink px-2 py-1 text-[0.72rem] uppercase tracking-[0.08em] ${statusTone(job.status)}`}>
                              {job.status}
                            </span>
                          </div>
                          <p className="m-0 break-words text-[0.75rem] uppercase tracking-[0.08em] text-ot-muted">
                            Requested by {job.requested_by}
                            {job.model_id ? ` / model ${job.model_id}` : ''}
                            {job.dataset_id ? ` / dataset ${job.dataset_id.slice(0, 8)}` : ''}
                          </p>
                        </div>

                        <div className="grid gap-1 text-right text-[0.72rem] uppercase tracking-[0.08em] text-ot-muted max-[720px]:text-left">
                          <span>created {formatTimestamp(job.created_at)}</span>
                          <span>heartbeat {formatTimestamp(job.heartbeat_at)}</span>
                          <span>finished {formatTimestamp(job.finished_at)}</span>
                        </div>
                      </div>

                      {job.error_message ? (
                        <p className="m-0 border-2 border-ot-red bg-[color-mix(in_srgb,var(--color-ot-red)_6%,var(--color-ot-surface))] px-3 py-3 text-[0.76rem] leading-[1.5] text-ot-red">
                          {job.error_message}
                        </p>
                      ) : null}
                    </article>
                  ))
                )}
              </div>
            </section>
          </div>
        </section>
      </div>
    </main>
  )
}
