import { startTransition, useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import {
  getAdminSemanticBaseModels,
  getAdminSemanticDatasets,
  getAdminSemanticJobs,
  getAdminSemanticModels,
  getAdminSemanticTrainOptions,
  queueSemanticDatasetJob,
  queueSemanticPromotion,
  queueSemanticTrainJob,
} from '../lib/adminApi'
import type {
  SemanticBaseModelOption,
  SemanticDatasetJobCreate,
  SemanticDatasetSummary,
  SemanticJobSummary,
  SemanticModelSummary,
  SemanticTrainAugmentationOption,
  SemanticTrainOptions,
} from '../types/api'
import {
  DEFAULT_DATASET_FORM,
  DEFAULT_TRAIN_FORM,
  type DatasetFormState,
  type TrainFormState,
} from './adminForms'
import { DatasetForm } from './DatasetForm'
import { DatasetTable } from './DatasetTable'
import { JobList } from './JobList'
import { ModelTable } from './ModelTable'
import { TrainForm } from './TrainForm'

type AdminSnapshot = {
  models: SemanticModelSummary[]
  jobs: SemanticJobSummary[]
  datasets: SemanticDatasetSummary[]
}

type AdminPageProps = {
  onLogout?: () => void
}

const FALLBACK_TRAIN_OPTIONS: SemanticTrainOptions = {
  epoch_min: 1,
  epoch_max: 10,
  batch_size_options: [4, 8, 16, 32, 64, 128, 256],
  embed_batch_size_options: [64, 128, 256, 512, 1024],
  augmentation_options: [
    {
      key: 'tag_pairs',
      label: 'Tag pairs',
      description: 'Positive pairs sampled from shared card tags.',
      default_enabled: true,
    },
    {
      key: 'tag_descriptions',
      label: 'Tag descriptions',
      description: 'Anchor text built from tag names and descriptions.',
      default_enabled: true,
    },
    {
      key: 'template_queries',
      label: 'Template queries',
      description: 'Synthetic search-style prompts generated from oracle text.',
      default_enabled: true,
    },
    {
      key: 'llm_queries',
      label: 'LLM queries',
      description: 'Synthetic queries generated by an LLM from card oracle text and metadata.',
      default_enabled: false,
    },
  ],
}

function defaultAugmentationKeys(options: SemanticTrainAugmentationOption[]) {
  return options.filter((option) => option.default_enabled).map((option) => option.key)
}

function serializeAugmentationKeys(keys: string[]) {
  const normalized = Array.from(new Set(keys.map((key) => key.trim()).filter(Boolean))).sort()
  return normalized.length === 0 ? 'none' : normalized.join(',')
}

export function AdminPage({ onLogout }: AdminPageProps) {
  const [snapshot, setSnapshot] = useState<AdminSnapshot>({ models: [], jobs: [], datasets: [] })
  const [baseModels, setBaseModels] = useState<SemanticBaseModelOption[]>([])
  const [trainOptions, setTrainOptions] = useState<SemanticTrainOptions>(FALLBACK_TRAIN_OPTIONS)
  const [form, setForm] = useState<TrainFormState>(DEFAULT_TRAIN_FORM)
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [datasetForm, setDatasetForm] = useState<DatasetFormState>(DEFAULT_DATASET_FORM)
  const [datasetSubmitting, setDatasetSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [notice, setNotice] = useState<string | null>(null)

  const activePromoteJob = useMemo(
    () => snapshot.jobs.find((job) => job.job_type === 'promote' && (job.status === 'pending' || job.status === 'running')) ?? null,
    [snapshot.jobs]
  )
  const selectedBaseModel = useMemo(
    () => baseModels.find((model) => model.key === form.base_model_key) ?? null,
    [baseModels, form.base_model_key]
  )

  const refreshBoard = useCallback(async (mode: 'initial' | 'refresh' = 'refresh') => {
    if (mode === 'initial') {
      setLoading(true)
    } else {
      setRefreshing(true)
    }

    try {
      const [models, jobs, allowedBaseModels, nextTrainOptions, datasets] = await Promise.all([
        getAdminSemanticModels(),
        getAdminSemanticJobs(),
        getAdminSemanticBaseModels(),
        getAdminSemanticTrainOptions(),
        getAdminSemanticDatasets(),
      ])
      startTransition(() => {
        setSnapshot({ models, jobs, datasets })
        setBaseModels(allowedBaseModels)
        setTrainOptions(nextTrainOptions)
        setForm((current) => {
          const nextBaseModelKey = allowedBaseModels.some((model) => model.key === current.base_model_key)
            ? current.base_model_key
            : allowedBaseModels[0]?.key ?? current.base_model_key
          const nextBatchSize = nextTrainOptions.batch_size_options.includes(current.batch_size)
            ? current.batch_size
            : nextTrainOptions.batch_size_options[0] ?? current.batch_size
          const nextEmbedBatchSize = nextTrainOptions.embed_batch_size_options.includes(current.embed_batch_size)
            ? current.embed_batch_size
            : nextTrainOptions.embed_batch_size_options[0] ?? current.embed_batch_size

          return {
            ...current,
            base_model_key: nextBaseModelKey,
            batch_size: nextBatchSize,
            embed_batch_size: nextEmbedBatchSize,
          }
        })
        setDatasetForm((current) => {
          const filtered = current.augmentation_keys.filter((key) =>
            nextTrainOptions.augmentation_options.some((o) => o.key === key)
          )
          return {
            ...current,
            augmentation_keys: filtered.length > 0 ? filtered : defaultAugmentationKeys(nextTrainOptions.augmentation_options),
          }
        })
        setError(null)
      })
    } catch (nextError) {
      setError(nextError instanceof Error ? nextError.message : 'Unable to load admin registry.')
    } finally {
      if (mode === 'initial') {
        setLoading(false)
      } else {
        setRefreshing(false)
      }
    }
  }, [])

  useEffect(() => {
    void refreshBoard('initial')
  }, [refreshBoard])

  const handleTrainField = useCallback(
    <K extends keyof TrainFormState>(key: K, value: TrainFormState[K]) => {
      setForm((current) => ({ ...current, [key]: value }))
    },
    []
  )

  const handleQueueTrain = useCallback(
    async (event: FormEvent<HTMLFormElement>) => {
      event.preventDefault()
      setSubmitting(true)
      setNotice(null)

      try {
        await queueSemanticTrainJob({
          ...form,
          requested_by: 'admin',
          model_slug: form.model_slug.trim(),
        })
        setNotice(`Queued train job for ${form.model_slug.trim() || 'new model'}.`)
        setForm((current) => ({
          ...DEFAULT_TRAIN_FORM,
          dataset_id: current.dataset_id,
          base_model_key: current.base_model_key,
          batch_size: current.batch_size,
          embed_batch_size: current.embed_batch_size,
        }))
        await refreshBoard('refresh')
      } catch (nextError) {
        setError(nextError instanceof Error ? nextError.message : 'Unable to queue train job.')
      } finally {
        setSubmitting(false)
      }
    },
    [form, refreshBoard]
  )

  const handlePromote = useCallback(
    async (modelId: number) => {
      setSubmitting(true)
      setNotice(null)

      try {
        await queueSemanticPromotion(modelId, {
          requested_by: 'admin',
          embed_batch_size: form.embed_batch_size,
        })
        setNotice(`Queued promotion for model ${modelId}.`)
        await refreshBoard('refresh')
      } catch (nextError) {
        setError(nextError instanceof Error ? nextError.message : 'Unable to queue promote job.')
      } finally {
        setSubmitting(false)
      }
    },
    [form.embed_batch_size, refreshBoard]
  )

  const handleQueueDataset = useCallback(
    async (event: FormEvent<HTMLFormElement>) => {
      event.preventDefault()
      setDatasetSubmitting(true)
      setNotice(null)
      try {
        const payload: SemanticDatasetJobCreate = {
          requested_by: 'admin',
          dataset_slug: datasetForm.dataset_slug.trim(),
          augmentation_mode: serializeAugmentationKeys(datasetForm.augmentation_keys),
        }
        await queueSemanticDatasetJob(payload)
        setNotice(`Dataset build queued: ${datasetForm.dataset_slug.trim()}`)
        setDatasetForm((current) => ({ ...current, dataset_slug: '' }))
        await refreshBoard('refresh')
      } catch (nextError) {
        setError(nextError instanceof Error ? nextError.message : 'Unable to queue dataset job.')
      } finally {
        setDatasetSubmitting(false)
      }
    },
    [datasetForm, refreshBoard]
  )

  return (
    <main className="relative min-h-screen overflow-x-clip bg-ot-bg text-ot-ink">
      <div className="fixed inset-y-0 left-0 z-10 w-1.5 bg-ot-red" aria-hidden="true" />
      <div
        className="pointer-events-none absolute inset-0 opacity-60"
        aria-hidden="true"
        style={{
          backgroundImage:
            'repeating-linear-gradient(to bottom, transparent 0, transparent 70px, rgba(17,17,17,0.05) 70px, rgba(17,17,17,0.05) 72px)',
        }}
      />

      <div className="relative z-20 mx-auto flex min-h-screen w-full max-w-[1560px] flex-col px-6 pb-10 pl-11 pt-6 max-[920px]:px-4 max-[920px]:pl-[30px]">
        <header className="grid gap-4 border-b-2 border-ot-ink pb-5 max-[920px]:gap-3">
          <div className="flex items-start justify-between gap-4 max-[920px]:flex-col max-[920px]:items-stretch">
            <div className="grid gap-2">
              <p className="eyebrow">Semantic Registry / Admin</p>
              <h1 className="m-0 max-w-[11ch] font-display text-[clamp(3.8rem,9vw,7rem)] font-black uppercase leading-[0.84] tracking-[-0.04em]">
                Registry board
              </h1>
            </div>

            <div className="grid w-full max-w-[320px] min-w-0 gap-0 self-start border-2 border-ot-ink bg-ot-surface max-[920px]:max-w-none">
              <a
                href="/"
                className="border-b-2 border-ot-ink px-4 py-3 font-display text-[1.1rem] font-black uppercase tracking-[-0.02em] transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] hover:bg-ot-ink hover:text-ot-bg"
              >
                Return to search
              </a>
              {onLogout ? (
                <button
                  type="button"
                  onClick={onLogout}
                  className="border-b-2 border-ot-ink px-4 py-3 text-left font-display text-[1.1rem] font-black uppercase tracking-[-0.02em] transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] hover:bg-ot-red hover:text-ot-bg"
                >
                  Sign out
                </button>
              ) : null}
              <button
                type="button"
                onClick={() => void refreshBoard('refresh')}
                className="border-b-2 border-ot-ink px-4 py-3 text-left font-display text-[1.1rem] font-black uppercase tracking-[-0.02em] transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] hover:bg-ot-ink hover:text-ot-bg active:opacity-80"
              >
                {refreshing ? 'Refreshing…' : 'Refresh board'}
              </button>
              <div className="grid grid-cols-4">
                <div className="overflow-hidden border-r-2 border-ot-ink px-2 py-2">
                  <p className="eyebrow">Models</p>
                  <p className="m-0 pt-1 font-display text-2xl font-black uppercase leading-none">{snapshot.models.length}</p>
                </div>
                <div className="overflow-hidden border-r-2 border-ot-ink px-2 py-2">
                  <p className="eyebrow">Datasets</p>
                  <p className="m-0 pt-1 font-display text-2xl font-black uppercase leading-none">{snapshot.datasets.length}</p>
                </div>
                <div className="overflow-hidden border-r-2 border-ot-ink px-2 py-2">
                  <p className="eyebrow">Queued</p>
                  <p className="m-0 pt-1 font-display text-2xl font-black uppercase leading-none">
                    {snapshot.jobs.filter((job) => job.status === 'pending' || job.status === 'running').length}
                  </p>
                </div>
                <div className="overflow-hidden px-2 py-2">
                  <p className="eyebrow">Pulse</p>
                  <p className="m-0 pt-1 font-display text-base font-black uppercase leading-none">
                    {refreshing ? 'syncing' : 'steady'}
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="grid gap-2 border-t-2 border-ot-ink pt-3 text-[0.78rem] uppercase tracking-[0.08em] text-ot-muted max-[900px]:text-[0.72rem]">
            <span>Queue new training runs, watch the worker heartbeat, and nominate the next active semantic model without leaving the app.</span>
            {activePromoteJob ? (
              <span className="text-ot-red">
                Promotion lane occupied by job #{activePromoteJob.id}. Clear it before promoting another model.
              </span>
            ) : (
              <span>Promotion lane is open.</span>
            )}
          </div>
        </header>

        {error ? (
          <div className="mt-4 border-2 border-ot-red bg-ot-surface px-4 py-3 text-[0.78rem] uppercase tracking-[0.08em] text-ot-red">
            {error}
          </div>
        ) : null}

        {notice ? (
          <div className="mt-4 border-2 border-ot-ink bg-ot-yellow px-4 py-3 text-[0.78rem] uppercase tracking-[0.08em] text-ot-ink">
            {notice}
          </div>
        ) : null}

        <section className="grid flex-1 grid-cols-[minmax(0,440px)_minmax(0,1fr)] gap-6 pt-6 max-[1180px]:grid-cols-1">
          <div className="grid h-fit gap-6">
            <DatasetForm
              form={datasetForm}
              setForm={setDatasetForm}
              onSubmit={handleQueueDataset}
              submitting={datasetSubmitting}
              loading={loading}
              augmentationOptions={trainOptions.augmentation_options}
            />
            <TrainForm
              form={form}
              onFieldChange={handleTrainField}
              onSubmit={handleQueueTrain}
              submitting={submitting}
              loading={loading}
              baseModels={baseModels}
              trainOptions={trainOptions}
              selectedBaseModel={selectedBaseModel}
              datasets={snapshot.datasets}
            />
          </div>

          <div className="grid min-w-0 self-start gap-6">
            <DatasetTable datasets={snapshot.datasets} loading={loading} />

            <ModelTable
              models={snapshot.models}
              loading={loading}
              submitting={submitting}
              activePromoteJob={activePromoteJob}
              onPromote={(modelId) => void handlePromote(modelId)}
            />

            <JobList jobs={snapshot.jobs} loading={loading} />
          </div>
        </section>
      </div>
    </main>
  )
}
