import { useCallback, useMemo, useState, type FormEvent } from 'react'
import { useIsFetching, useQueryClient } from '@tanstack/react-query'
import type { SemanticDatasetJobCreate, SemanticTrainAugmentationOption, SemanticTrainOptions } from '../types/api'
import {
  DEFAULT_DATASET_FORM,
  DEFAULT_TRAIN_FORM,
  type DatasetFormState,
  type TrainFormState,
} from './adminForms'
import { useAdminBaseModels, useAdminDatasets, useAdminJobs, useAdminModels, useAdminTrainOptions } from './adminQueries'
import { useQueueDatasetJob, useQueuePromotion, useQueueTrainJob } from './adminMutations'
import { DatasetForm } from './DatasetForm'
import { DatasetTable } from './DatasetTable'
import { JobList } from './JobList'
import { ModelTable } from './ModelTable'
import { TrainForm } from './TrainForm'

type AdminPageProps = {
  onLogout?: () => void
}

const FALLBACK_TRAIN_OPTIONS: SemanticTrainOptions = {
  epoch_min: 1,
  epoch_max: 10,
  batch_size_options: [4, 8, 16, 32, 64, 128, 256],
  embed_batch_size_options: [64, 128, 256, 512, 1024],
  augmentation_options: [
    { key: 'tag_pairs', label: 'Tag pairs', description: 'Positive pairs sampled from shared card tags.', default_enabled: true },
    { key: 'tag_descriptions', label: 'Tag descriptions', description: 'Anchor text built from tag names and descriptions.', default_enabled: true },
    { key: 'template_queries', label: 'Template queries', description: 'Synthetic search-style prompts generated from oracle text.', default_enabled: true },
    { key: 'llm_queries', label: 'LLM queries', description: 'Synthetic queries generated by an LLM from card oracle text and metadata.', default_enabled: false },
  ],
}

function defaultAugmentationKeys(options: SemanticTrainAugmentationOption[]) {
  return options.filter((option) => option.default_enabled).map((option) => option.key)
}

function serializeAugmentationKeys(keys: string[]) {
  const normalized = Array.from(new Set(keys.map((key) => key.trim()).filter(Boolean))).sort()
  return normalized.length === 0 ? 'none' : normalized.join(',')
}

function firstErrorMessage(errors: (Error | null | undefined)[]): string | null {
  for (const error of errors) {
    if (error) return error.message
  }
  return null
}

export function AdminPage({ onLogout }: AdminPageProps) {
  const queryClient = useQueryClient()

  const modelsQuery = useAdminModels()
  const jobsQuery = useAdminJobs()
  const datasetsQuery = useAdminDatasets()
  const baseModelsQuery = useAdminBaseModels()
  const trainOptionsQuery = useAdminTrainOptions()

  const datasetMutation = useQueueDatasetJob()
  const trainMutation = useQueueTrainJob()
  const promoteMutation = useQueuePromotion()

  const [form, setForm] = useState<TrainFormState>(DEFAULT_TRAIN_FORM)
  const [datasetForm, setDatasetForm] = useState<DatasetFormState>(DEFAULT_DATASET_FORM)
  const [notice, setNotice] = useState<string | null>(null)

  const models = useMemo(() => modelsQuery.data ?? [], [modelsQuery.data])
  const jobs = useMemo(() => jobsQuery.data ?? [], [jobsQuery.data])
  const datasets = useMemo(() => datasetsQuery.data ?? [], [datasetsQuery.data])
  const baseModels = useMemo(() => baseModelsQuery.data ?? [], [baseModelsQuery.data])
  const trainOptions = trainOptionsQuery.data ?? FALLBACK_TRAIN_OPTIONS

  const loading =
    modelsQuery.isLoading || jobsQuery.isLoading || datasetsQuery.isLoading || baseModelsQuery.isLoading || trainOptionsQuery.isLoading
  const refreshing = useIsFetching({ queryKey: ['admin'] }) > 0
  const submitting = trainMutation.isPending || promoteMutation.isPending
  const datasetSubmitting = datasetMutation.isPending

  const error = firstErrorMessage([
    modelsQuery.error,
    jobsQuery.error,
    datasetsQuery.error,
    baseModelsQuery.error,
    trainOptionsQuery.error,
    datasetMutation.error,
    trainMutation.error,
    promoteMutation.error,
  ])

  const activePromoteJob = useMemo(
    () => jobs.find((job) => job.job_type === 'promote' && (job.status === 'pending' || job.status === 'running')) ?? null,
    [jobs]
  )

  // Effective (render-time) form derived from raw state + latest server
  // options. When the user's last pick isn't in the current option set we
  // substitute the first valid option; raw state stays untouched, so when
  // the user changes the selection it drives effective and raw together.
  const effectiveForm: TrainFormState = useMemo(() => {
    const baseModelKey =
      baseModels.length === 0 || baseModels.some((m) => m.key === form.base_model_key)
        ? form.base_model_key
        : baseModels[0]?.key ?? form.base_model_key
    const batchSize = trainOptions.batch_size_options.includes(form.batch_size)
      ? form.batch_size
      : trainOptions.batch_size_options[0] ?? form.batch_size
    const embedBatchSize = trainOptions.embed_batch_size_options.includes(form.embed_batch_size)
      ? form.embed_batch_size
      : trainOptions.embed_batch_size_options[0] ?? form.embed_batch_size
    return { ...form, base_model_key: baseModelKey, batch_size: batchSize, embed_batch_size: embedBatchSize }
  }, [form, baseModels, trainOptions])

  const effectiveDatasetForm: DatasetFormState = useMemo(() => {
    const filtered = datasetForm.augmentation_keys.filter((key) =>
      trainOptions.augmentation_options.some((o) => o.key === key)
    )
    const augmentationKeys =
      filtered.length > 0 ? filtered : defaultAugmentationKeys(trainOptions.augmentation_options)
    return { ...datasetForm, augmentation_keys: augmentationKeys }
  }, [datasetForm, trainOptions])

  const selectedBaseModel = useMemo(
    () => baseModels.find((model) => model.key === effectiveForm.base_model_key) ?? null,
    [baseModels, effectiveForm.base_model_key]
  )

  const handleRefresh = useCallback(() => {
    void queryClient.invalidateQueries({ queryKey: ['admin'] })
  }, [queryClient])

  const handleTrainField = useCallback(
    <K extends keyof TrainFormState>(key: K, value: TrainFormState[K]) => {
      setForm((current) => ({ ...current, [key]: value }))
    },
    []
  )

  const handleQueueTrain = useCallback(
    async (event: FormEvent<HTMLFormElement>) => {
      event.preventDefault()
      setNotice(null)
      try {
        await trainMutation.mutateAsync({
          ...effectiveForm,
          requested_by: 'admin',
          model_slug: effectiveForm.model_slug.trim(),
        })
        setNotice(`Queued train job for ${effectiveForm.model_slug.trim() || 'new model'}.`)
        setForm((current) => ({
          ...DEFAULT_TRAIN_FORM,
          dataset_id: current.dataset_id,
          base_model_key: current.base_model_key,
          batch_size: current.batch_size,
          embed_batch_size: current.embed_batch_size,
        }))
      } catch {
        // error surfaces via trainMutation.error
      }
    },
    [effectiveForm, trainMutation]
  )

  const handlePromote = useCallback(
    async (modelId: string) => {
      setNotice(null)
      try {
        await promoteMutation.mutateAsync({
          modelId,
          payload: { requested_by: 'admin', embed_batch_size: effectiveForm.embed_batch_size },
        })
        setNotice(`Queued promotion for model ${modelId}.`)
      } catch {
        // error surfaces via promoteMutation.error
      }
    },
    [effectiveForm.embed_batch_size, promoteMutation]
  )

  const handleQueueDataset = useCallback(
    async (event: FormEvent<HTMLFormElement>) => {
      event.preventDefault()
      setNotice(null)
      const payload: SemanticDatasetJobCreate = {
        requested_by: 'admin',
        dataset_slug: effectiveDatasetForm.dataset_slug.trim(),
        augmentation_mode: serializeAugmentationKeys(effectiveDatasetForm.augmentation_keys),
      }
      try {
        await datasetMutation.mutateAsync(payload)
        setNotice(`Dataset build queued: ${effectiveDatasetForm.dataset_slug.trim()}`)
        setDatasetForm((current) => ({ ...current, dataset_slug: '' }))
      } catch {
        // error surfaces via datasetMutation.error
      }
    },
    [effectiveDatasetForm, datasetMutation]
  )

  return (
    <main className="relative min-h-screen overflow-x-clip bg-ot-bg text-ot-ink">
      <div className="fixed inset-y-0 left-0 z-10 w-1.5 bg-ot-red" aria-hidden="true" />
      <div
        className="pointer-events-none absolute inset-0 opacity-60"
        aria-hidden="true"
        style={{
          backgroundImage:
            'repeating-linear-gradient(to bottom, transparent 0, transparent 70px, rgba(17,17,17,0.05) 70px, rgba(17,17,17,0.05) 72px)',
        }}
      />

      <div className="relative z-20 mx-auto flex min-h-screen w-full max-w-[1560px] flex-col px-6 pb-10 pl-11 pt-6 max-[920px]:px-4 max-[920px]:pl-[30px]">
        <header className="grid gap-4 border-b-2 border-ot-ink pb-5 max-[920px]:gap-3">
          <div className="flex items-start justify-between gap-4 max-[920px]:flex-col max-[920px]:items-stretch">
            <div className="grid gap-2">
              <p className="eyebrow">Semantic Registry / Admin</p>
              <h1 className="m-0 max-w-[11ch] font-display text-[clamp(3.8rem,9vw,7rem)] font-black uppercase leading-[0.84] tracking-[-0.04em]">
                Registry board
              </h1>
            </div>

            <div className="grid w-full max-w-[320px] min-w-0 gap-0 self-start border-2 border-ot-ink bg-ot-surface max-[920px]:max-w-none">
              <a
                href="/"
                className="border-b-2 border-ot-ink px-4 py-3 font-display text-[1.1rem] font-black uppercase tracking-[-0.02em] transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] hover:bg-ot-ink hover:text-ot-bg"
              >
                Return to search
              </a>
              {onLogout ? (
                <button
                  type="button"
                  onClick={onLogout}
                  className="border-b-2 border-ot-ink px-4 py-3 text-left font-display text-[1.1rem] font-black uppercase tracking-[-0.02em] transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] hover:bg-ot-red hover:text-ot-bg"
                >
                  Sign out
                </button>
              ) : null}
              <button
                type="button"
                onClick={handleRefresh}
                className="border-b-2 border-ot-ink px-4 py-3 text-left font-display text-[1.1rem] font-black uppercase tracking-[-0.02em] transition-colors duration-150 ease-[cubic-bezier(0.25,1,0.5,1)] hover:bg-ot-ink hover:text-ot-bg active:opacity-80"
              >
                {refreshing ? 'Refreshing…' : 'Refresh board'}
              </button>
              <div className="grid grid-cols-4">
                <div className="overflow-hidden border-r-2 border-ot-ink px-2 py-2">
                  <p className="eyebrow">Models</p>
                  <p className="m-0 pt-1 font-display text-2xl font-black uppercase leading-none">{models.length}</p>
                </div>
                <div className="overflow-hidden border-r-2 border-ot-ink px-2 py-2">
                  <p className="eyebrow">Datasets</p>
                  <p className="m-0 pt-1 font-display text-2xl font-black uppercase leading-none">{datasets.length}</p>
                </div>
                <div className="overflow-hidden border-r-2 border-ot-ink px-2 py-2">
                  <p className="eyebrow">Queued</p>
                  <p className="m-0 pt-1 font-display text-2xl font-black uppercase leading-none">
                    {jobs.filter((job) => job.status === 'pending' || job.status === 'running').length}
                  </p>
                </div>
                <div className="overflow-hidden px-2 py-2">
                  <p className="eyebrow">Pulse</p>
                  <p className="m-0 pt-1 font-display text-base font-black uppercase leading-none">
                    {refreshing ? 'syncing' : 'steady'}
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="grid gap-2 border-t-2 border-ot-ink pt-3 text-[0.78rem] uppercase tracking-[0.08em] text-ot-muted max-[900px]:text-[0.72rem]">
            <span>Queue new training runs, watch the worker heartbeat, and nominate the next active semantic model without leaving the app.</span>
            {activePromoteJob ? (
              <span className="text-ot-red">
                Promotion lane occupied by job #{activePromoteJob.id}. Clear it before promoting another model.
              </span>
            ) : (
              <span>Promotion lane is open.</span>
            )}
          </div>
        </header>

        {error ? (
          <div className="mt-4 border-2 border-ot-red bg-ot-surface px-4 py-3 text-[0.78rem] uppercase tracking-[0.08em] text-ot-red">
            {error}
          </div>
        ) : null}

        {notice ? (
          <div className="mt-4 border-2 border-ot-ink bg-ot-yellow px-4 py-3 text-[0.78rem] uppercase tracking-[0.08em] text-ot-ink">
            {notice}
          </div>
        ) : null}

        <section className="grid flex-1 grid-cols-[minmax(0,440px)_minmax(0,1fr)] gap-6 pt-6 max-[1180px]:grid-cols-1">
          <div className="grid h-fit gap-6">
            <DatasetForm
              form={effectiveDatasetForm}
              setForm={setDatasetForm}
              onSubmit={handleQueueDataset}
              submitting={datasetSubmitting}
              loading={loading}
              augmentationOptions={trainOptions.augmentation_options}
            />
            <TrainForm
              form={effectiveForm}
              onFieldChange={handleTrainField}
              onSubmit={handleQueueTrain}
              submitting={submitting}
              loading={loading}
              baseModels={baseModels}
              trainOptions={trainOptions}
              selectedBaseModel={selectedBaseModel}
              datasets={datasets}
            />
          </div>

          <div className="grid min-w-0 self-start gap-6">
            <DatasetTable datasets={datasets} loading={loading} />

            <ModelTable
              models={models}
              loading={loading}
              submitting={submitting}
              activePromoteJob={activePromoteJob}
              onPromote={(modelId) => void handlePromote(modelId)}
            />

            <JobList jobs={jobs} loading={loading} />
          </div>
        </section>
      </div>
    </main>
  )
}
