from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

EPOCH_MIN = 1
EPOCH_MAX = 10

TRAIN_BATCH_SIZE_OPTIONS = (4, 8, 16, 32, 64, 128, 256)
EMBED_BATCH_SIZE_OPTIONS = (64, 128, 256, 512, 1024)

TRAIN_AUGMENTATION_TAG_PAIRS = "tag_pairs"
TRAIN_AUGMENTATION_TAG_DESCRIPTIONS = "tag_descriptions"
TRAIN_AUGMENTATION_TEMPLATE_QUERIES = "template_queries"
TRAIN_AUGMENTATION_LLM_QUERIES = "llm_queries"


@dataclass(frozen=True)
class TrainAugmentationOption:
    key: str
    label: str
    description: str
    default_enabled: bool = True


TRAIN_AUGMENTATION_OPTIONS = (
    TrainAugmentationOption(
        key=TRAIN_AUGMENTATION_TAG_PAIRS,
        label="Tag pairs",
        description="Positive pairs sampled from shared card tags.",
    ),
    TrainAugmentationOption(
        key=TRAIN_AUGMENTATION_TAG_DESCRIPTIONS,
        label="Tag descriptions",
        description="Anchor text built from tag names and descriptions.",
    ),
    TrainAugmentationOption(
        key=TRAIN_AUGMENTATION_TEMPLATE_QUERIES,
        label="Template queries",
        description="Synthetic search-style prompts generated from oracle text.",
    ),
    TrainAugmentationOption(
        key=TRAIN_AUGMENTATION_LLM_QUERIES,
        label="LLM queries",
        description="Synthetic queries generated by an LLM from card oracle text and metadata.",
        default_enabled=False,
    ),
)

TRAIN_AUGMENTATION_OPTION_KEYS = tuple(option.key for option in TRAIN_AUGMENTATION_OPTIONS)
DEFAULT_TRAIN_AUGMENTATION_KEYS = tuple(
    option.key for option in TRAIN_AUGMENTATION_OPTIONS if option.default_enabled
)
DEFAULT_TRAIN_AUGMENTATION_MODE = ",".join(DEFAULT_TRAIN_AUGMENTATION_KEYS)


def validate_train_batch_size(value: int) -> int:
    if value not in TRAIN_BATCH_SIZE_OPTIONS:
        raise ValueError(f"Batch size must be one of: {', '.join(str(item) for item in TRAIN_BATCH_SIZE_OPTIONS)}.")
    return value


def validate_embed_batch_size(value: int) -> int:
    if value not in EMBED_BATCH_SIZE_OPTIONS:
        raise ValueError(
            f"Embed batch size must be one of: {', '.join(str(item) for item in EMBED_BATCH_SIZE_OPTIONS)}."
        )
    return value


def normalize_train_augmentation_keys(keys: Iterable[str]) -> tuple[str, ...]:
    normalized = sorted({str(key).strip() for key in keys if str(key).strip()})
    invalid = [key for key in normalized if key not in TRAIN_AUGMENTATION_OPTION_KEYS]
    if invalid:
        raise ValueError(
            f"Unsupported augmentation selection: {', '.join(invalid)}. "
            f"Expected any of: {', '.join(TRAIN_AUGMENTATION_OPTION_KEYS)}."
        )
    return tuple(normalized)


def parse_train_augmentation_mode(mode: str | None) -> tuple[str, ...]:
    if mode is None:
        return DEFAULT_TRAIN_AUGMENTATION_KEYS

    normalized_mode = mode.strip()
    if not normalized_mode or normalized_mode == "none":
        return ()

    return normalize_train_augmentation_keys(normalized_mode.split(","))


def serialize_train_augmentation_mode(keys: Iterable[str]) -> str:
    normalized = normalize_train_augmentation_keys(keys)
    if not normalized:
        return "none"
    return ",".join(normalized)
